### PR TITLE
Force agregate

### PR DESCRIPTION
**Pull request by adkron**
Sometimes we want to disable the aggregation on the front end time, and push it to a background task like resque. This commit allows the aggregate_tags! function to be able to be called even if aggregation is set to false.

### CODE REVIEW

**Comment by ches** [comment]
Ah, makes sense. The forced return definitely feels like an overprotective parent, your use case makes it clear. You can omit the `self.class` clutter though, since `aggregate_tags?` is being delegated.

**Comment by ches** [comment]
Oh, I'm sorry -- it isn't, but it probably can be :-)

**Comment by ches** [comment]
Cherry-picked the first change and made the delegation change, thanks!

FWIW my pedantic opinion is that `.rvmrc` is a user's local preference and should be in your global `excludesfile`. It makes sense for team consistency on _private_ projects -- basically the same situations where you'd check in `Gemfile.lock` -- where it can be tracked with `git add --force .rvmrc`. &lt;/rant>

**Comment by adkron** [comment]
Adding .rvmrc to the ignore file for the project allows people to have
.rvmrc ignored only on certain projects and not on their entire box. Unless
you are planning on adding a .rvmrc file to the repo I don't understand why
the local ignore is not on an OSS project. This could lead to people
accidentally checking in their own .rvmrc files because they are not
ignoring it for all projects on the computer.

On Fri, Aug 26, 2011 at 1:53 AM, ches <
reply@reply.github.com>wrote:

> Cherry-picked the first change and made the delegation change, thanks!
> 
> FWIW my pedantic opinion is that `.rvmrc` is a user's local preference and
> should be in your global `excludesfile`. It makes sense for team consistency
> on _private_ projects -- basically the same situations where you'd check in
> `Gemfile.lock` -- where it can be tracked with `git add --force .rvmrc`.
> &lt;/rant>
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ches/mongoid_taggable/pull/1#issuecomment-1910414

## 

Amos King
http://dirtyInformation.com
http://github.com/Adkron

**Comment by ches** [comment]
You can think of it this way:

I don't use TextMate, and I don't really want to be bothered adding `*.tmproj` in the `.gitignore` for all my projects -- TextMate users should take responsibility for doing that globally on their systems so they don't accidentally commit them. RVM isn't much different in this respect -- maybe I want to use rbenv for instance. Everyone reading commit logs shouldn't be bothered with ignore commits for `.rvmrc`, `.rbenv-version`, IDE mess or whatever else comes along until the end of time that is a personal preference to use -- I'd rather encourage people to break that habit.

I know it's a silly argument, it's just a pet peeve of mine. You are free to disagree on your projects :-)

**Pull request closed without merging**
