### PR TITLE
Fixed class_inheritable_attribute deprecation warning in rails 3.1

### PR DESCRIPTION
**Pull request by JangoSteve**
I kept getting deprecation warnings for `class_inheritable_attribute` in Rails 3.1. I've updated a few other gems for this exact thing, so I went ahead and updated this too. See [the docs](http://apidock.com/rails/Class/class_attribute) for more info.

### CODE REVIEW

**Comment by JangoSteve** [comment]
Nevermind, don't pull this in yet. This isn't behaving as expected.

**Comment by JangoSteve** [comment]
OK, actually ran through the mongoid_taggable specs this time and managed to figure out what was happening. I had missed the call to `write_inheritable_attribute` before. I've updated this pull request and everything seems to be working.

**Comment by ches** [comment]
Thanks, knew this was coming but hadn't upgraded an app yet so didn't have the deprecation warnings itch. Was also thinking for some reason that it was going to be a backwards-incompatible fix, so glad it's straightforward.

**Comment by JangoSteve** [comment]
Yeah, I've seen some people do a check to use the old way if less than Rails 3.1 and the new way if Rails 3.1 or greater, like this:

```
self.send( (Rails.version < "3.1" ? :class_inheritable_accessor : :class_attribute), :tags, :etc)
```

But I never understood that because I thought the entire reason `:class_inheritable_accessor` was deprecated was because `class_attribute` already existed. Anyway, if anything arises where some aspect of this turns out not to be backwards compatible, that's an option.

**Comment by ches** [comment]
It's available from 3.0 onward, so the check makes sense for that. Since Mongoid hasn't supported < 3.0 since it changed drastically (2.0), there's a good excuse not to support it in this plugin :-)

**Pull request merged**
