### PR TITLE
Add tags_before_type_cast method

### PR DESCRIPTION
**Pull request by tmaier**
I added a [type_before_type_cast](http://api.rubyonrails.org/classes/ActionView/Helpers/InstanceTag.html#method-c-value_before_type_cast) method.

basically it does the same as https://gist.github.com/1172956 but by providing a type_before_type_cast method which is then used by Rails FormHelper.

This way it is independent of SimpleForm and has no negative side effects on the generated HTML.

### CODE REVIEW

**Comment by tmaier** [comment]
I have to admit, I'm not sure if this is the best way to do this, especially because of ActiveSupport::Concern.

But as stackexchange is down at the moment, I don't know it any better (Yes, I love to blame someone else)

**Comment by ches** [comment]
That looks reasonable -- could you add a test case and update the usage info in the `README`?

**Comment by tmaier** [comment]
Added spec for
- the default case
- with a different separator
- with another field name for tags

**Comment by tmaier** [comment]
Hey @ches,

I just wanted to know if you could merge this pull request or if you need any further work from my side on this?

**Comment by ches** [comment]
Sorry for losing track of this, thanks for the reminder -- it looks good, I'll try to get it merged after wrapping up client work today. Might take this opportunity to add Travis CI to the project :smile:

**Comment by ches** [comment]
Merged, thank you!

**Comment by tmaier** [comment]
Thank you @ches!

Great to see travis support!

**Pull request closed without merging**
